[package]
name = "tcg"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.0"
rand = "0.9.2"
thiserror = "2.0.17"
strum = { version = "0.27.2", features = ["derive"] }
